### PR TITLE
Added more DBUS options + updated GUI

### PR DESCRIPTION
**Pull request by terrycain**
BOOM - see commits for more details.

Ok what did I do...

Converted the Tray applet to use Python3 as the other GUI is in Python3 I thought I might as well update.

Updated packaging scripts - removed python2 stuff as library isn't 100% compatible. 

Added another DBUS endpoint which the daemon interacts with the set_key_row driver file. This allows for us to set colours in userspace. It accepts an array of bytes which are in the format of 1byte for row then 22 1*3 byte RGB values. So total 67 Bytes. If you want to set multiple rows then you can concatenate the byte strings and send any multiple of 67 bytes.

Created a keyboard colour class in python to interact with the new dbus command. This forms the binary array in memory and you can use that to send to DBUS. This class takes in a `key` which is like 'K' or '4' or 'LEFTSHIFT' etc... and a colour value, ideally this class is used for representing the keyboard's colour state in memory.

Remvoved globals from the GUI app, reworked it a ton to no longer need root permissions and it now uses DBUS.

### CODE REVIEW

**Comment by lah7** [comment]
Wow, seriously impressive stuff. Good job!

One more thing: Consider another commit to add to the copyright (to credit your code) and remove the instructions from the README that ask to set up a sudoers file.

**Comment by terrycain** [comment]
Good point.

**Comment by terrycain** [comment]
At some point to be 'consistent' we should go through and either add the copyright header to all the files, or remove them and have one main copyright document.

**Comment by lah7** [comment]
I'd opt for a header on all unattributed files - give credit where it's due - and always transparency if the file is opened when installed to the system.

**Comment by lah7** [comment]
Few notes:
 * Can no longer CTRL+C out of Tray Applet
 * Chroma Controller loads a white screen, no error, just "`Successfully connected to dbus service.
`" - is this working on your end?

**Comment by terrycain** [comment]
All worked on my end. Did you load up the new daemon as well?

**Comment by lah7** [comment]
Nope, still no go. I uninstalled, rebooted, compiled, packaged then installed... all successful, but the Chroma GUI is still plain white. Which distro by any chance? Ubuntu MATE 15.10 here.

Will try figuring out what's happened... :confused:

**Comment by terrycain** [comment]
Ubuntu 14.04 LTS. Will try again once I get back to the computer but am
sure it worked for me. What's `ls /usr/lib/python3/dist-packages/razer`
list? There should be 2 main python files

**Comment by lah7** [comment]
> daemon_dbus.py  __init__.py  keyboard.py  __pycache__

I think it's somewhere around line 404 ( :smile: Yes, literally!) and 429, but I could be wrong.

**Comment by terrycain** [comment]
404 and 429 of what file?

**Comment by lah7** [comment]
`chroma_controller.py`

**Comment by lah7** [comment]
Absolutely weird, I `git clone`'d the repository and by pure magic, it's working again. Must of had something to do with the ZIP download of your repository.

**Comment by terrycain** [comment]
Ha, no worries. Do you install it using the packaging commands making a .deb?

**Comment by lah7** [comment]
From the working directory, I execute:
`make -s all`
`./package_for_ubuntu.sh`
`sudo service razer_bcd stop`
`sudo dpkg -r razer-chroma-driver`
`sudo dpkg -i /tmp/tmp*.deb`

Some real strange quirks have been going on with this repository.

**Comment by terrycain** [comment]
Yeah. Also for the record technically just running
```
make
./packagefordebian...
dpkg -i razer.dpkg
```
Should just work as technically it should automatically stop the razer_bcd
daemon and replace the currently installed package

**Pull request merged**
